/**
 * LUNVO Provider Registry — single source of truth for every AI provider.
 * Adding a provider = adding ONE entry here. No adapter code needed.
 *
 * adapter: 'openai-compatible' | 'gemini' | 'anthropic'
 * Excluded (not chat-completion providers): Voyage (embeddings), Soniox (speech),
 * ZeroEntropy (retrieval), Mem0/Supermemory (memory), MCP Sampling (protocol),
 * Browser AI / Codex CLI / Gemini CLI (tools), Hindsight/Spark (internal).
 */

export type ProviderCategory =
  | "frontier"
  | "aggregator"
  | "fast-inference"
  | "open-cheap"
  | "privacy"
  | "gateway"
  | "local"
  | "enterprise";

export interface ProviderDef {
  id: string;
  name: string;
  category: ProviderCategory;
  adapter: "openai-compatible" | "gemini" | "anthropic";
  baseURL?: string;
  defaultModel: string;
  models: string[];
  keyUrl?: string;
  keyHint?: string;
  color: string;
  iconSlug?: string;
  freeTier?: boolean;
  local?: boolean;
  coming?: boolean;
}

const P = (def: ProviderDef): ProviderDef => def;

export const PROVIDER_REGISTRY: ProviderDef[] = [
  // ---------------- FRONTIER ----------------
  P({
    id: "openai",
    name: "OpenAI",
    category: "frontier",
    adapter: "openai-compatible",
    baseURL: "https://api.openai.com/v1",
    defaultModel: "gpt-4o-mini",
    models: ["gpt-4o-mini", "gpt-4o", "gpt-4.1", "gpt-4.1-mini", "o4-mini"],
    keyUrl: "https://platform.openai.com/api-keys",
    keyHint: "sk-...",
    color: "#10A37F",
    iconSlug: "openai",
  }),
  P({
    id: "anthropic",
    name: "Anthropic",
    category: "frontier",
    adapter: "anthropic",
    defaultModel: "claude-3-5-sonnet-20241022",
    models: ["claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022", "claude-opus-4-20250514"],
    keyUrl: "https://console.anthropic.com/settings/keys",
    keyHint: "sk-ant-...",
    color: "#D97757",
    iconSlug: "anthropic",
  }),
  P({
    id: "gemini",
    name: "Google Gemini",
    category: "frontier",
    adapter: "gemini",
    defaultModel: "gemini-2.0-flash",
    models: ["gemini-2.0-flash", "gemini-2.0-flash-lite", "gemini-1.5-pro"],
    keyUrl: "https://aistudio.google.com/apikey",
    keyHint: "AIza...",
    color: "#4285F4",
    iconSlug: "google",
    freeTier: true,
  }),
  P({
    id: "xai",
    name: "xAI Grok",
    category: "frontier",
    adapter: "openai-compatible",
    baseURL: "https://api.x.ai/v1",
    defaultModel: "grok-3-mini",
    models: ["grok-3-mini", "grok-3", "grok-4"],
    keyUrl: "https://console.x.ai",
    color: "#1A1A1A",
    iconSlug: "x",
    freeTier: true,
  }),
  P({
    id: "deepseek",
    name: "DeepSeek",
    category: "frontier",
    adapter: "openai-compatible",
    baseURL: "https://api.deepseek.com/v1",
    defaultModel: "deepseek-chat",
    models: ["deepseek-chat", "deepseek-reasoner"],
    keyUrl: "https://platform.deepseek.com/api_keys",
    color: "#4D6BFE",
    iconSlug: "deepseek",
    freeTier: true,
  }),
  P({
    id: "mistral",
    name: "Mistral",
    category: "frontier",
    adapter: "openai-compatible",
    baseURL: "https://api.mistral.ai/v1",
    defaultModel: "mistral-small-latest",
    models: ["mistral-small-latest", "mistral-large-latest", "open-mistral-nemo"],
    keyUrl: "https://console.mistral.ai/api-keys",
    color: "#FF7000",
    iconSlug: "mistralai",
    freeTier: true,
  }),

  // ---------------- AGGREGATORS ----------------
  P({
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    adapter: "openai-compatible",
    baseURL: "https://openrouter.ai/api/v1",
    defaultModel: "meta-llama/llama-3.3-70b-instruct",
    models: [
      "meta-llama/llama-3.3-70b-instruct",
      "deepseek/deepseek-chat",
      "anthropic/claude-3.5-sonnet",
      "google/gemini-2.0-flash-001",
    ],
    keyUrl: "https://openrouter.ai/settings/keys",
    color: "#6467F2",
    iconSlug: "openrouter",
    freeTier: true,
  }),
  P({
    id: "github-models",
    name: "GitHub Models",
    category: "aggregator",
    adapter: "openai-compatible",
    baseURL: "https://models.github.ai/inference",
    defaultModel: "openai/gpt-4.1-mini",
    models: [
      "openai/gpt-4.1-mini",
      "openai/gpt-4.1",
      "meta/Llama-4-Scout-17B-16E",
      "deepseek/DeepSeek-R1",
    ],
    keyUrl: "https://github.com/settings/tokens",
    keyHint: "github_pat_... (models:read)",
    color: "#24292F",
    iconSlug: "github",
    freeTier: true,
  }),
  P({
    id: "huggingface",
    name: "HuggingFace Router",
    category: "aggregator",
    adapter: "openai-compatible",
    baseURL: "https://router.huggingface.co/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen3-32B", "deepseek-ai/DeepSeek-V3"],
    keyUrl: "https://huggingface.co/settings/tokens",
    keyHint: "hf_...",
    color: "#B8860B",
    iconSlug: "huggingface",
    freeTier: true,
  }),

  // ---------------- FAST INFERENCE ----------------
  P({
    id: "groq",
    name: "Groq",
    category: "fast-inference",
    adapter: "openai-compatible",
    baseURL: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
    keyUrl: "https://console.groq.com/keys",
    keyHint: "gsk_...",
    color: "#F55036",
    iconSlug: "groq",
    freeTier: true,
  }),
  P({
    id: "cerebras",
    name: "Cerebras",
    category: "fast-inference",
    adapter: "openai-compatible",
    baseURL: "https://api.cerebras.ai/v1",
    defaultModel: "llama3.1-8b",
    models: ["llama3.1-8b", "llama-3.3-70b", "qwen-3-32b"],
    keyUrl: "https://cloud.cerebras.ai",
    color: "#F97316",
    freeTier: true,
  }),
  P({
    id: "sambanova",
    name: "SambaNova",
    category: "fast-inference",
    adapter: "openai-compatible",
    baseURL: "https://api.sambanova.ai/v1",
    defaultModel: "Meta-Llama-3.1-8B-Instruct",
    models: [
      "Meta-Llama-3.1-8B-Instruct",
      "Meta-Llama-3.3-70B-Instruct",
      "DeepSeek-R1-Distill-Llama-70B",
    ],
    keyUrl: "https://cloud.sambanova.ai/apis",
    color: "#36B37E",
    freeTier: true,
  }),
  P({
    id: "nvidia",
    name: "NVIDIA NIM",
    category: "fast-inference",
    adapter: "openai-compatible",
    baseURL: "https://integrate.api.nvidia.com/v1",
    defaultModel: "meta/llama-3.3-70b-instruct",
    models: [
      "meta/llama-3.3-70b-instruct",
      "deepseek-ai/deepseek-r1",
      "moonshotai/kimi-k2-instruct",
    ],
    keyUrl: "https://build.nvidia.com",
    color: "#5A8A00",
    iconSlug: "nvidia",
    freeTier: true,
  }),
  P({
    id: "fireworks",
    name: "Fireworks AI",
    category: "fast-inference",
    adapter: "openai-compatible",
    baseURL: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    models: [
      "accounts/fireworks/models/llama-v3p3-70b-instruct",
      "accounts/fireworks/models/deepseek-v3",
    ],
    keyUrl: "https://fireworks.ai/account/api-keys",
    color: "#7C3AED",
    freeTier: true,
  }),

  // ---------------- OPEN & CHEAP ----------------
  P({
    id: "together",
    name: "Together AI",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    models: [
      "meta-llama/Llama-3.3-70B-Instruct-Turbo",
      "deepseek-ai/DeepSeek-V3",
      "Qwen/Qwen3-32B",
    ],
    keyUrl: "https://api.together.ai/settings/api-keys",
    color: "#0F6FFF",
  }),
  P({
    id: "deepinfra",
    name: "DeepInfra",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://deepinfra.com/v1/openai",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3", "Qwen/Qwen3-32B"],
    keyUrl: "https://deepinfra.com/dash/api_keys",
    color: "#0E9BA8",
    freeTier: true,
  }),
  P({
    id: "hyperbolic",
    name: "Hyperbolic",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.hyperbolic.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
    keyUrl: "https://app.hyperbolic.xyz/settings",
    color: "#7C3AED",
    freeTier: true,
  }),
  P({
    id: "novita",
    name: "Novita AI",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.novita.ai/v3/openai",
    defaultModel: "meta-llama/llama-3.3-70b-instruct",
    models: ["meta-llama/llama-3.3-70b-instruct", "deepseek/deepseek-v3"],
    keyUrl: "https://novita.ai/dashboard/key",
    color: "#16A34A",
    freeTier: true,
  }),
  P({
    id: "nebius",
    name: "Nebius Token Factory",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.tokenfactory.nebius.com/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
    keyUrl: "https://tokenfactory.nebius.com",
    color: "#4F46E5",
    freeTier: true,
  }),
  P({
    id: "lambda-ai",
    name: "Lambda AI",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.lambda.ai/v1",
    defaultModel: "llama-3.1-405b-instruct-fp8",
    models: ["llama-3.1-405b-instruct-fp8", "deepseek-r1", "hermes-3-llama-3.1-405b"],
    keyUrl: "https://cloud.lambda.ai",
    color: "#DC2626",
  }),
  P({
    id: "scaleway",
    name: "Scaleway",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.scaleway.ai/v1",
    defaultModel: "qwen3-32b",
    models: ["qwen3-32b", "mistral-small-3.1-24b-instruct", "llama-3.3-70b-instruct"],
    keyUrl: "https://console.scaleway.com/generative-api/keys",
    color: "#5109C6",
    iconSlug: "scaleway",
    freeTier: true,
  }),
  P({
    id: "baseten",
    name: "Baseten",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://inference.baseten.co/v1",
    defaultModel: "deepseek-ai/DeepSeek-V3-0324",
    models: ["deepseek-ai/DeepSeek-V3-0324", "meta-llama/Llama-4-Maverick-17B-128E-Instruct"],
    keyUrl: "https://app.baseten.co/settings/keys",
    color: "#D97706",
  }),
  P({
    id: "crusoe",
    name: "Crusoe",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.crusoecloud.ai/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct"],
    keyUrl: "https://cloud.crusoecloud.ai",
    color: "#0284C7",
  }),
  P({
    id: "ionet",
    name: "IO.NET Intelligence",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.iointelligence.com/v1",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3"],
    keyUrl: "https://cloud.io.net",
    color: "#84CC16",
  }),
  P({
    id: "replicate",
    name: "Replicate",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.replicate.com/v1",
    defaultModel: "meta/meta-llama-3.1-405b-instruct",
    models: ["meta/meta-llama-3.1-405b-instruct", "openai/gpt-4o-mini"],
    keyUrl: "https://replicate.com/account/api-tokens",
    keyHint: "r8_...",
    color: "#B45309",
    iconSlug: "replicate",
    freeTier: true,
  }),
  P({
    id: "minimax",
    name: "MiniMax",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-Text-01",
    models: ["MiniMax-Text-01", "abab6.5s-chat"],
    keyUrl: "https://www.minimax.io/platform/user-center/basic-information/interface-key",
    color: "#EF4444",
  }),
  P({
    id: "moonshot",
    name: "Moonshot Kimi",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.moonshot.ai/v1",
    defaultModel: "kimi-k2-turbo-preview",
    models: ["kimi-k2-turbo-preview", "kimi-k2-instruct", "moonshot-v1-8k"],
    keyUrl: "https://platform.moonshot.ai/console/api-keys",
    color: "#374151",
  }),
  P({
    id: "zhipu",
    name: "Zhipu GLM",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-4.5",
    models: ["glm-4.5", "glm-4-plus", "glm-4-flash"],
    keyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    color: "#3B82F6",
    freeTier: true,
  }),
  P({
    id: "qwen",
    name: "Qwen (Alibaba)",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen-plus",
    models: ["qwen-plus", "qwen-max", "qwen-turbo"],
    keyUrl: "https://bailian.console.alibabacloud.com",
    color: "#EA580C",
    iconSlug: "alibabacloud",
    freeTier: true,
  }),
  P({
    id: "upstage",
    name: "Upstage Solar",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.upstage.ai/v1/solar",
    defaultModel: "solar-pro",
    models: ["solar-pro", "solar-mini"],
    keyUrl: "https://console.upstage.ai",
    color: "#6D28D9",
    freeTier: true,
  }),
  P({
    id: "sarvam",
    name: "Sarvam AI",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.sarvam.ai/v1",
    defaultModel: "sarvam-m",
    models: ["sarvam-m"],
    keyUrl: "https://dashboard.sarvam.ai",
    color: "#F97316",
  }),
  P({
    id: "clarifai",
    name: "Clarifai",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.clarifai.com/v2/ext/openai/v1",
    defaultModel: "openai/gpt-4o-mini",
    models: ["openai/gpt-4o-mini", "meta/llama-3.3-70b-instruct"],
    keyUrl: "https://clarifai.com/settings/security/api-keys",
    color: "#0284C7",
  }),
  P({
    id: "chutes",
    name: "Chutes",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://api.chutes.ai/v1",
    defaultModel: "deepseek-ai/DeepSeek-V3",
    models: ["deepseek-ai/DeepSeek-V3", "meta-llama/Llama-3.3-70B-Instruct"],
    keyUrl: "https://chutes.ai/app/api-keys",
    color: "#8B5CF6",
  }),
  P({
    id: "digitalocean",
    name: "DigitalOcean Gradient",
    category: "open-cheap",
    adapter: "openai-compatible",
    baseURL: "https://inference.do-ai.run/v1",
    defaultModel: "llama3.3-70b-instruct",
    models: ["llama3.3-70b-instruct", "gpt-oss-120b"],
    keyUrl: "https://cloud.digitalocean.com/gen-ai",
    color: "#2563EB",
    iconSlug: "digitalocean",
    freeTier: true,
  }),

  // ---------------- PRIVACY ----------------
  P({
    id: "venice",
    name: "Venice AI",
    category: "privacy",
    adapter: "openai-compatible",
    baseURL: "https://api.venice.ai/api/v1",
    defaultModel: "llama-3.3-70b",
    models: ["llama-3.3-70b", "deepseek-r1-671b"],
    keyUrl: "https://venice.ai/settings/api-keys",
    color: "#DB2777",
    freeTier: true,
  }),
  P({
    id: "perplexity",
    name: "Perplexity Sonar",
    category: "privacy",
    adapter: "openai-compatible",
    baseURL: "https://api.perplexity.ai",
    defaultModel: "sonar",
    models: ["sonar", "sonar-pro", "sonar-reasoning"],
    keyUrl: "https://www.perplexity.ai/settings/api",
    color: "#20808D",
    iconSlug: "perplexity",
  }),
  P({
    id: "cohere",
    name: "Cohere",
    category: "privacy",
    adapter: "openai-compatible",
    baseURL: "https://api.cohere.ai/compatibility/v1",
    defaultModel: "command-r7b-12-2024",
    models: ["command-r7b-12-2024", "command-a-03-2025"],
    keyUrl: "https://dashboard.cohere.com/api-keys",
    color: "#39594D",
    iconSlug: "cohere",
  }),

  // ---------------- GATEWAYS (account-specific URLs) ----------------
  P({
    id: "vercel-gateway",
    name: "Vercel AI Gateway",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "https://ai-gateway.vercel.sh/v1",
    defaultModel: "openai/gpt-4o-mini",
    models: [
      "openai/gpt-4o-mini",
      "anthropic/claude-sonnet-4",
      "meta-llama/llama-3.3-70b-instruct",
    ],
    keyUrl: "https://vercel.com/dashboard",
    color: "#111111",
    iconSlug: "vercel",
    freeTier: true,
  }),
  P({
    id: "cloudflare-workers",
    name: "Cloudflare Workers AI",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "",
    defaultModel: "@cf/meta/llama-3.1-8b-instruct",
    models: ["@cf/meta/llama-3.1-8b-instruct", "@cf/qwen/qwen1.5-14b-chat-awq"],
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    keyHint:
      "Paste your account endpoint: https://api.cloudflare.com/client/v4/accounts/<ID>/ai/v1",
    color: "#F48120",
    iconSlug: "cloudflare",
    freeTier: true,
  }),
  P({
    id: "aihubmix",
    name: "AIHubMix",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "https://aihubmix.com/v1",
    defaultModel: "gpt-4o-mini",
    models: ["gpt-4o-mini", "claude-3-5-sonnet-20241022"],
    keyUrl: "https://aihubmix.com",
    color: "#6366F1",
  }),
  P({
    id: "302ai",
    name: "302.AI",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "https://api.302.ai/v1",
    defaultModel: "gpt-4o-mini",
    models: ["gpt-4o-mini", "deepseek-chat"],
    keyUrl: "https://302.ai",
    color: "#7C3AED",
  }),
  P({
    id: "langdb",
    name: "LangDB",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "https://api.us.langdb.ai/v1",
    defaultModel: "openai/gpt-4o-mini",
    models: ["openai/gpt-4o-mini", "anthropic/claude-3.5-sonnet"],
    keyUrl: "https://dashboard.us.langdb.ai",
    color: "#0EA5E9",
    freeTier: true,
  }),
  P({
    id: "edenai",
    name: "Eden AI",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "",
    defaultModel: "openai/gpt-4o-mini",
    models: ["openai/gpt-4o-mini"],
    keyUrl: "https://app.eden-ai.run",
    keyHint: "Paste your Eden AI OpenAI-compatible endpoint",
    color: "#D97706",
  }),
  P({
    id: "dify",
    name: "Dify",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "",
    defaultModel: "gpt-4o-mini",
    models: ["gpt-4o-mini"],
    keyUrl: "https://dify.ai",
    keyHint: "Paste your Dify app OpenAI-compatible endpoint",
    color: "#1677FF",
  }),
  P({
    id: "letta",
    name: "Letta",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "https://api.letta.com/v1",
    defaultModel: "letta-free",
    models: ["letta-free"],
    keyUrl: "https://app.letta.com",
    color: "#FF6B35",
  }),
  P({
    id: "sap-aic",
    name: "SAP AI Core",
    category: "gateway",
    adapter: "openai-compatible",
    baseURL: "",
    defaultModel: "gpt-4o-mini",
    models: ["gpt-4o-mini"],
    keyUrl: "https://help.sap.com/docs/sap-ai-core",
    keyHint: "Paste your SAP AI Core deployment endpoint",
    color: "#0FAAFF",
    iconSlug: "sap",
  }),

  // ---------------- LOCAL ----------------
  P({
    id: "ollama",
    name: "Ollama (Local)",
    category: "local",
    adapter: "openai-compatible",
    baseURL: "http://localhost:11434/v1",
    defaultModel: "llama3.2",
    models: ["llama3.2", "llama3.1", "qwen2.5", "mistral"],
    color: "#6B7280",
    iconSlug: "ollama",
    local: true,
    freeTier: true,
  }),
  P({
    id: "lmstudio",
    name: "LM Studio (Local)",
    category: "local",
    adapter: "openai-compatible",
    baseURL: "http://localhost:1234/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    color: "#4B5563",
    local: true,
    freeTier: true,
  }),
  P({
    id: "llamacpp",
    name: "llama.cpp (Local)",
    category: "local",
    adapter: "openai-compatible",
    baseURL: "http://localhost:8080/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    color: "#6B7280",
    local: true,
    freeTier: true,
  }),
  P({
    id: "jan",
    name: "Jan (Local)",
    category: "local",
    adapter: "openai-compatible",
    baseURL: "http://localhost:1337/v1",
    defaultModel: "local-model",
    models: ["local-model"],
    color: "#4B5563",
    local: true,
    freeTier: true,
  }),
  P({
    id: "ollama-cloud",
    name: "Ollama Cloud",
    category: "local",
    adapter: "openai-compatible",
    baseURL: "https://ollama.com/v1",
    defaultModel: "gpt-oss:120b",
    models: ["gpt-oss:120b", "gpt-oss:20b", "qwen3:32b"],
    keyUrl: "https://ollama.com",
    color: "#374151",
    freeTier: true,
  }),

  // ---------------- ENTERPRISE (coming — need dedicated adapters) ----------------
  P({
    id: "azure-openai",
    name: "Azure OpenAI",
    category: "enterprise",
    adapter: "openai-compatible",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "gpt-4o-mini"],
    keyUrl: "https://portal.azure.com",
    color: "#0078D4",
    iconSlug: "azure",
    coming: true,
  }),
  P({
    id: "amazon-bedrock",
    name: "Amazon Bedrock",
    category: "enterprise",
    adapter: "openai-compatible",
    defaultModel: "anthropic.claude-3-5-sonnet",
    models: ["anthropic.claude-3-5-sonnet", "meta.llama3-3-70b-instruct"],
    keyUrl: "https://console.aws.amazon.com/bedrock",
    color: "#FF9900",
    iconSlug: "amazonwebservices",
    coming: true,
  }),
  P({
    id: "google-vertex",
    name: "Google Vertex AI",
    category: "enterprise",
    adapter: "gemini",
    defaultModel: "gemini-2.0-flash",
    models: ["gemini-2.0-flash"],
    keyUrl: "https://console.cloud.google.com/vertex-ai",
    color: "#4285F4",
    iconSlug: "googlecloud",
    coming: true,
  }),
];

export function getProviderDef(id: string): ProviderDef | undefined {
  return PROVIDER_REGISTRY.find((p) => p.id === id);
}

export function searchProviders(query: string): ProviderDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return PROVIDER_REGISTRY;
  return PROVIDER_REGISTRY.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.id.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}

export const CATEGORY_META: Record<ProviderCategory, { label: string; color: string }> = {
  frontier: { label: "Frontier", color: "#004AC6" },
  aggregator: { label: "Aggregators", color: "#7C3AED" },
  "fast-inference": { label: "Fast Inference", color: "#EA580C" },
  "open-cheap": { label: "Open & Cheap", color: "#059669" },
  privacy: { label: "Privacy", color: "#DB2777" },
  gateway: { label: "Gateways", color: "#0284C7" },
  local: { label: "Local & Free", color: "#6B7280" },
  enterprise: { label: "Enterprise", color: "#92400E" },
};
